### ISSUE TITLE
Db not found

### ISSUE THREAD

**Issue by brokenseal** [TIBCOSoftware/JS-FDSample#3]
Hello guys,
some days ago I noticed this issue https://github.com/marianol/FreshDeliveryDemo/issues/6 on your previous repository, I suggest you fix the README file otherwise other people like me will become frustrated as well.

Cheers,
Davide

**Comment by ernestoongaro** [comment]
Thanks @brokenseal - was it a matter of configuring psql to point to localhost?

**Comment by brokenseal** [comment]
It was a matter of pointing to the correct port for the local postgresql database

**Comment by ernestoongaro** [comment]
Thanks Davide - I wonder if this is worth mentioning in the README guide.
You get the option to change your postgres port at installation time
(otherwise it uses the default port which is 5432). If its on default port
then psql will run without having to give it the --port command

On Mon, Feb 15, 2016 at 11:15 AM, Davide Callegari <notifications@github.com

**Comment by brokenseal** [comment]
I'm on OSX and I wasn't asked anything during installation time :)
